config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'authors/authors'
  get 'books/books'
  get 'home/index'
  get 'home/about'

  #resources
  resources :books
  resources :authors



  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author


  validates :title, presence: true
  validates :publisher, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def authors
    @authors = Author.all
  end

  def show
   @author = Author.find(params[:id])
  end

  def new
   @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author, notice: "save author successfully"
    else
      redirect_to :new , notice: "unable to save"
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)

      redirect_to authors_authors_path, notice: "Update successfully"
    else

      redirect_to edit: , notice: "unable to update author"
    end

  end

  def destroy
    @author = Author.find(params[:id])

    if @author.destroy
      redirect_to authors_authors_path , notice: "author deleted"
    else
      redirect_to authors_authors_path, notice: "unable to delete"
    end


  end

  private

  def author_params
    params.require(:author).permit(:name , :email)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def books
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end


  def new
   @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book , notice: 'Book was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
     render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:success] = 'Book was successfully deleted.'
      redirect_to books_books_path
    else
      redirect_to books_books_path, notice: "something went wrong.."
    end
  end


private

  def book_params
    params.require(:book).permit(:title, :publisher , :price, :author_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>" class="card mb-3">
  <div class="card-body">
    <h3> Name </h3>
    <h5 class="card-title">
      <%= author.name %>
    </h5>
    <p class="card-text">
      <strong>Email:</strong> <%= author.email %>
    </p>
  
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with model: @author, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_area :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/authors/authors.html.erb
<%= stylesheet_link_tag "books.css", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>
<h3> Author List </h3>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Open</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= link_to "Open", author_path(author), class: "btn btn-dark" %></td>
        <td><%= link_to "Edit", edit_author_path(author), class: "btn btn-dark" %></td>
        <td><%=  button_to "Delete", author, method: :delete , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<%= link_to "Create New Author" , new_author_path, class: "btn btn-primary" %>



app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render "form", author: @author %>

app/views/authors/new.html.erb
<h1>Add Author</h1>

<%= render "form"  %>

app/views/authors/show.html.erb

<%= render "author" , author: @author %>
<%= link_to "Back to Author", authors_authors_path , class:"btn btn-dark" %>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="card mb-3">
  <div class="card-body">
    <h3> Title </h3>
    <h5 class="card-title">
      <%= book.title %>
    </h5>
    <p class="card-text">
      <strong>Publisher:</strong> <%= book.publisher %>
    </p>
    <p class="card-text">
      <strong>Price:</strong> $<%= book.price %>
    </p>
    <p class="card-text">
      <strong>Author:</strong> <%= book.author.name %>
    </p>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with model: @book local: true do |form| %>
  <div class="form-group">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter title' %>
  </div>

  <div class="form-group">
    <%= form.label :publisher, class: 'form-label' %>
    <%= form.text_area :publisher, class: 'form-control', placeholder: 'Enter publisher' %>
  </div>

  <div class="form-group">
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, class: 'form-control', placeholder: 'Enter price' %>
  </div>

  <div class="form-group">
    <%= form.label :author, class: 'form-label' %>
    <%= form.text_field :author_id, class: 'form-control', placeholder: 'Enter author ID' %>
  </div>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/books/books.html.erb
<%= stylesheet_link_tag "books.css", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>
<h3> Books List </h3>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Publisher</th>
      <th>Price</th>
      <th>Author</th>
      <th>show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.publisher %></td>
        <td><%= book.price %></td>
        <td><%= book.author.name %></td>
        <td><%= link_to "Show", book_path(book), class: "btn btn-dark" %></td>
        <td><%= link_to "Edit", edit_book_path(book), class: "btn btn-dark" %></td>
        <td><%=  button_to "Delete", book, method: :delete , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<%= link_to "Create New Book" , new_book_path, class: "btn btn-primary" %>



app/views/books/edit.html.erb
<h1>Editing post</h1>

<%= render "form", book: @book %>

app/views/books/new.html.erb
<h1>Add post</h1>

<%= render "form" %>

app/views/books/show.html.erb

<%= render "book" , book: @book%>
<%= link_to "Back to Books", books_books_path , class:"btn btn-dark" %>



app/views/home/about.html.erb
<h3> About ramdom story </h3>
<p> Once upon a time, in a quaint little village nestled between rolling hills and lush forests, there lived a curious group of creatures known as the Whimsies. These whimsical beings were unlike any other inhabitants of the land. Each Whimsy possessed a unique talent or ability that brought joy and wonder to the world around them.

At the heart of the village stood a towering oak tree, its branches reaching high into the sky like outstretched arms embracing the heavens. This majestic tree was not just a symbol of strength and beauty; it was also the home of the Whimsies' most cherished gathering place – the Whimsy Café.

The Whimsy Café was a cozy haven where creatures of all shapes and sizes would gather to share stories, laughter, and, of course, delicious treats. From the mischievous Pixie Bites to the enchanting Unicorn Lattes, every concoction served at the café was infused with a dash of magic and a sprinkle of whimsy.

But the true magic of the Whimsy Café lay in its patrons – the colorful characters who frequented its tables day after day. There was Luna the Dreamweaver, whose stories could transport you to far-off lands with a single word. Then there was Oliver the Owl, the café's resident scholar, whose vast knowledge of ancient lore never failed to captivate his audience.

And let's not forget about Rosie the Rabbit, the café's beloved pastry chef, whose delectable creations were rumored to have the power to mend broken hearts and lift spirits on even the gloomiest of days. </p>

app/views/home/index.html.erb
<div class="container-fluid py-5 " >
    <section class="row">
      <div class="col-md-6 mb-3">
       <%= image_tag("wallpaper.jpg", alt: "Ocean Bookstore Photo 1", class: "img-fluid rounded") %>
      <div class="col-md-6">
        <p>Welcome to Ocean Bookstore, your one-stop shop for all your literary needs! We offer a vast collection of books across various genres, from classic bestsellers to the latest releases.</p>
        <p>Whether you're a seasoned reader or just starting your bookworm journey, we have something for everyone. Browse our shelves and discover new worlds, revisit your favorites, and lose yourself in the magic of storytelling.</p>
      </div>
    </section>

    <section class="row mt-5">
      </section>
  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>

  </head>
   <body class="bg-light">
    
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
    <%= link_to "BOOK OCEAN"  , home_index_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

      <div class="navbar-nav">
        
        <%= link_to "Book"  , books_books_path, class: "nav-link active" %>
        <%= link_to "Author"  , authors_authors_path, class: "nav-link active" %>
        
        <%= link_to "About", home_about_path , class: "nav-link active" %>
        
      </div>
    </div>
  </div>
</nav>
   
    <div class ="container">
     <%= yield %>
    </div>
  </body>
</html>